version: "3.9"

services:
  task-traker:
    image: openjdk:17.0.2-jdk-slim-bullseye
    container_name: task-tracker
    depends_on:
      - mysql
    volumes:
      - ./target/task-tracker.jar:/home/service.jar
    ports:
      - "5388:8443"
    command: java -jar /home/service.jar
    restart: on-failure
  mysql:
    image: amd64/mysql:5-debian
    container_name: task-tracker-mysql
    command: --init-file /data/application/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tasktracker_db
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass
    volumes:
      - tasks_db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
volumes:
  tasks_db: